# Generated by Django 2.2.4 on 2019-08-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Todo_name', models.TextField(max_length=140)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
